create table t_user (
    id bigint generated by default as identity,
    login varchar(255) unique not null,
    password_hash varchar(255) not null,
    primary key (id)
);

create index idx_user_login on t_user (login);