create table t_withdrawal (
    id bigint generated by default as identity,
    order_number varchar(255) not null,
    sum numeric(10, 2) not null,
    processed_at timestamp with time zone not null,
    user_id bigint not null
);

alter table t_withdrawal add constraint fk_withdrawal_user_id foreign key (user_id) references t_user;
