create table t_order (
    id bigint generated by default as identity,
    number varchar(255) unique not null,
    status varchar(255) not null,
    accrual numeric(10, 2) not null default 0,
    uploaded_at timestamp with time zone not null,
    user_id bigint
);

alter table t_order add constraint fk_order_user_id foreign key (user_id) references t_user;

create index idx_order_status on t_order (status);